![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [1]:
import numpy as np

my_array = np.arange(10)
print(my_array)
print()
print(my_array[::-2]) 




[0 1 2 3 4 5 6 7 8 9]

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [18]:
my_array[-2:-4:-1]


array([8, 7])

## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [19]:
my_array[2::-1]

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [5]:
import numpy as np
javi = np.arange(1,21)
javi = javi.reshape(4,5)

print(javi)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [6]:
javi[::-1, ::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [11]:
javi[:2,:2]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [13]:
print(javi)

javi[::2,::2]


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [23]:
print(javi)

print()

betis = javi[:3,::]
print(betis)

betis[:3,::-1]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [24]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

mask = [True, False, False, True,False]
x[mask]

array(['Loro', 'Loro'], dtype='<U5')

In [9]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

mask = np.where(x=="Loro")
print(mask)

x[mask]

(array([0, 3], dtype=int64),)


array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [7]:
import numpy as np

secu = np.arange(1,21)
secu

secu = np.random.randint(1,21, size = (2,5,2))
print(secu)

#hacer reshape np.arange(20).reshape(2,5,2) tambien es válido. 


[[[16 18]
  [16 10]
  [16 20]
  [18  2]
  [ 5  3]]

 [[13 16]
  [ 6 13]
  [ 7  9]
  [13 19]
  [19 18]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [10]:
javi = np.arange(1,21)
javi = javi.reshape(4,5)

print(javi)

javi[4::-1,4::-1]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [80]:
arra0 = np.zeros(10)
arra0
arra0 = np.array(arra0)
# print(arra0)
print(f"Cada item del array ocupa {arra0.itemsize} bytes")
print(f"El array ocupa {arra0.nbytes} bytes")

# print(np.where(arra0[4]== 1,1,arra0))
# filtro4 = [[arra0[4]==1]]

# print(arra0[filtro4])

# print(np.where([[arra0[4]]],1,arra0))

arra0_sub = arra0[:]
arra0_sub[4] = 1

print(arra0_sub)



Cada item del array ocupa 8 bytes
El array ocupa 80 bytes
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [15]:
vector1 = np.arange(10,50)
print(vector1)

vector1[49::-1]
#tambien se puede hacer np.flip para invertir

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [19]:
vector2 = [1,2,0,0,4,0]

vector2 = np.array(vector2)

vector2 = np.where(vector2 != 0)
print(vector2)

#np.nonzero funcion para sacar los indices donde los elementos no son cero.

(array([0, 1, 4], dtype=int64),)


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [35]:
matriz_ale = np.random.randint(0,10, size = (1,10,10))
matriz_ale

# print(f"El valor mínimo de la matriz es {min(matriz_ale)} y el máximo es {max(matriz_ale)}")

print(matriz_ale)
print()

print(f"El valor minimo de la matriz es {matriz_ale.min()}")
print(f"El valor máximo de la matriz es {matriz_ale.max()}")

[[[4 2 1 7 5 4 3 9 6 4]
  [9 3 1 4 1 2 0 1 8 1]
  [8 4 5 8 6 0 8 1 4 7]
  [5 8 0 5 7 9 8 9 0 6]
  [3 4 1 2 4 9 8 9 7 8]
  [0 2 8 3 8 3 8 5 0 8]
  [0 5 5 3 5 5 7 8 0 2]
  [7 7 0 2 7 4 6 3 6 0]
  [7 5 5 3 5 5 4 9 2 4]
  [3 2 7 0 9 6 4 6 3 6]]]

El valor minimo de la matriz es 0
El valor máximo de la matriz es 9


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [41]:
UDA = np.arange(30)
UDA

print(np.mean(UDA))

print("UDA = Unión Deportiva Almeria ;)")
#np.random.random() saca valores entre 0 y 1 
#np.random.randnt(10) saca con la desviacion estandar

14.5
UDA = Unión Deportiva Almeria ;)


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [18]:
import numpy as np 
ma2D = np.ones((4,4))


ma2D[1:3,1:3] = 0
print(ma2D)

#jugar tambien con el -1 para referirse a la ultima fila o columna



[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [29]:
a = np.zeros((8,8))

a[::2,1::2] = 1
a[1::2,::2] = 1
print(a)

 

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [33]:
a

np.tile(a,2)

array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.]])

## Ejercicio 9
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [36]:
import numpy as np 

cinco = np.random.randint(1,15, size = (1,5,5))

media5 = np.mean(cinco)

conmedia = cinco - 6.16

ejercicio9 = conmedia / np.std(cinco)
ejercicio9

array([[[-0.92564002,  1.71067649,  0.24605621, -0.92564002,
          0.24605621],
        [-0.04686785, -0.63271596,  0.83190432, -0.92564002,
          2.2965246 ],
        [ 0.53898026,  0.24605621,  1.12482838,  0.24605621,
         -0.33979191],
        [ 1.71067649,  1.12482838,  1.41775243,  2.2965246 ,
         -1.51148813],
        [ 0.24605621,  0.83190432,  1.41775243,  0.83190432,
          0.24605621]]])

## Ejercicio 10
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [43]:
ejer10 = np.arange(11)

ejer10[3:9] = -1
ejer10

mask = [True, True, True, False, False, False, False, False, False, True, True]

ejer10 = ejer10[mask]
ejer10

array([ 0,  1,  2,  9, 10])

## Ejercicio 11
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [2]:
import numpy as np

flota = np.full((10,10), (" "))

flota[0,1] = "O"
flota[1,1] = "O"
flota[1,3] = "O"
flota[1,4] = "O"
flota[1,5] = "O"
flota[1,6] = "O"

print(flota)
print()

flota[1,4] = "X"
flota[2,1] = "-"

print(flota)


[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]

[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'X' 'O' 'O' ' ' ' ' ' ']
 [' ' '-' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [14]:
# import numpy as np

# np.random.seed(23)
# np.array(10)

# flotas[np.random.randint(10, size = 4), np.random.randint(10, size = 4)] = np.barco

while flota == np.full((10,10), (" ")):
    
    #np.random.randint(4,size= (1, [[4,1]]) | np.random.randint(4,size = (1,[[1,4]]))
    break
    

SyntaxError: invalid syntax (2865034318.py, line 10)

In [41]:
from operator import index
import numpy as np
while True:
        if (pos_x >=0 and pos_x<=9) and (pos_y>=0 and pos_y<=9):
                pos_x = int(input("Introduzca posicion X:(Valores entre 0 y 9)"))
                pos_y = int(input("Introduzca posicion Y:(Valores entre 0 y 9)"))

tablero[1,5]="O"
tablero = np.full(fill_value = ' ', shape = (10, 10))


if tablero== "X"
        print()
elif tablero==0

else


for x in tablero:
        for y in tablero:
                 #tablero[pos_x,pos_y] == 'X'

                if  (tablero[pos_x,pos_y] == 'X'):
                        print("Posicion ocupada con disparo")
                        pos_x = int(input("vuelva a introducir disparo en posicion X:(Valores entre 0 y 9)"))
                        pos_y = int(input("vuelva a introducir disparo en posicion Y:(Valores entre 0 y 9)"))
                elif tablero[pos_x,pos_y] == 'O':
                        print("impacto")
                
                else:
                      break

    
print(tablero)


[[' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]
